version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true
    networks:
      - mcp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/collections"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  qdrant-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3456:3456"
    environment:
      - PORT=3456
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAME=agent-ren3
      - LOG_LEVEL=debug
    networks:
      - mcp_network
    depends_on:
      qdrant:
        condition: service_healthy
    restart: unless-stopped

networks:
  mcp_network:
    driver: bridge

volumes:
  qdrant_data:
    driver: local